Traffic light plugin
RoboticaUtnFrba/create_autonomy pull request #111
Opened 2019-10-31 15:48 UTC by LucasJSch

## This PR's goal is to add a traffic light to the autorace map. For this purpose several files were created and modified:

- **Traffic light plugin** (.cpp and .h files). This plugin makes the processing for changing the traffic light's color.
- **World time publisher** (.cpp and .h files). This plugin helps the first mentioned plugin to know how much time has passed since it changed the light's color.
- **Traffic light model definition** (.confing and .sdf files). In these files the visual model for the traffic light is defined.
- **autorace.world**. This file was modified for allowing to spawn the traffic light.
- **ca_gazebo's CMakeLists**. This file was modified for allowing the two new plugins to be compiled.

## To do:
- Pass the time for every color as a parameter in the SDF file.

## Pictures of the traffic light

![red](https://user-images.githubusercontent.com/37854249/67962417-d4e99c00-fbdb-11e9-9db5-ea5036bcfe93.png)
![yellow](https://user-images.githubusercontent.com/37854249/67962442-ddda6d80-fbdb-11e9-91e4-ffdc42d5eb82.png)
![green](https://user-images.githubusercontent.com/37854249/67962462-e59a1200-fbdb-11e9-8009-cee0db4f38fa.png)

2019-10-31 15:49 UTC, LucasJSch commented
# Ready for review

2019-11-06 16:52 UTC, eborghi10 requested changes
I left some comments, thanks for pushing it!

2019-11-06 16:52 UTC, eborghi10 commented on ca_gazebo/CMakeLists.txt
> +				  traffic_light_plugin
Wrong indentation.

2019-11-06 16:52 UTC, eborghi10 commented on ca_gazebo/CMakeLists.txt
> +	add_library(create_bumper_plugin src/create_bumper_plugin.cpp)
Revert this change.

2019-11-06 16:52 UTC, eborghi10 commented on ca_gazebo/src/traffic_light_plugin.cpp
> +        commandSubscriber = this->data_ptr->node->Subscribe("/gazebo/EmptyWorld/WorldTime_topic", &GazeboTrafficLight::time_update_cb, this);
Why don't you get the time from `/gazebo/default/world_stats`?

2019-11-06 16:52 UTC, eborghi10 commented on ca_gazebo/src/traffic_light_plugin.cpp
> +            if(this->next_color_ == "red")
I believe this logic can be done much easier but I don't have a clue now on how to do it.

2019-11-06 16:52 UTC, eborghi10 commented on ca_gazebo/src/traffic_light_plugin.cpp
> +            if(this->next_color_ == "red")
You can use a `std::map` that uses `this->next_color_` as key and its value is the `ignition::math::Color`.

2020-02-19 23:48 UTC, eborghi10 commented
Closing this PR because #134 fixes the conflicts with `kinetic-devel`.

2020-02-19 23:48 UTC, closed without merging