Added yaml file for correct opening of empty_world simulation
RoboticaUtnFrba/create_autonomy pull request #97
Opened 2019-09-13 20:04 UTC by LucasJSch

empty_world simulation wasn't working in previous commit. Fixed it.

2019-09-13 20:05 UTC, LucasJSch commented
# Ready for review

2019-09-13 20:44 UTC, eborghi10 requested changes
One minor comment, PTAL.

2019-09-13 20:44 UTC, eborghi10 commented on navigation/ca_move_base/maps/empty.yaml
> +image: playground.pgm
[This parameter](http://wiki.ros.org/map_server#YAML_format) should point to a `pgm` file that corresponds to an empty environment.

I recommend you to compare you approach with this one ([empty_world](https://github.com/utexas-bwi/segbot_rocon/tree/bc96568f23b917d80744c6730d3adb76b31b2f55/segbot_concert_services/maps/empty_world)) and also include the missing `pgm`.

2019-09-20 17:12 UTC, LucasJSch commented
# Ready for review

2019-09-20 20:37 UTC, eborghi10 approved these changes

2019-09-20 20:38 UTC, merged